name: CI

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATADOG_API_KEY_CONFIGURED: ${{ secrets.DATADOG_API_KEY != '' }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v5
        with:
          go-version: "1.26.3"

      - name: Cache Go modules
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-1.26.3-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-1.26.3-

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Format check
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "The following files are not formatted correctly:"
            gofmt -s -l .
            exit 1
          fi

      - name: Vet
        run: go vet ./...

      - name: Configure Datadog Test Optimization
        if: ${{ env.DATADOG_API_KEY_CONFIGURED == 'true' }}
        uses: datadog/test-visibility-github-action@cdf298ef8277c8c3bec321499084ce5d9e4ff1e8 # v2.10.0
        with:
          languages: go
          api_key: ${{ secrets.DATADOG_API_KEY }}
          site: datadoghq.com
          service: ddtest

      - name: Run tests
        run: go test -race -coverpkg=./... -coverprofile=coverage.out -covermode=atomic ./...
        env:
          DD_ENV: ci

      - name: Upload coverage report to Datadog
        if: ${{ env.DATADOG_API_KEY_CONFIGURED == 'true' }}
        uses: DataDog/coverage-upload-github-action@6c4bd935248daa6f0ef94e3e6ba71ad5ad079998 # v1.0.3
        with:
          api_key: ${{ secrets.DATADOG_API_KEY }}
          site: datadoghq.com
          files: coverage.out
          format: go-coverprofile
          version: v5.19.0

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v5
        with:
          go-version: "1.26.3"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v6
        with:
          version: v2.11.4
          args: --timeout=5m
