name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@e75c3e80bcde46e322cd5845ae46582947c9becd # v5
        with:
          go-version: "1.25"

      - name: Build binaries
        run: make release

      - name: Create Release and Upload Assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          gh release create "pre-release-$SHORT_SHA" \
            --title "Pre-release $SHORT_SHA" \
            --prerelease \
            dist/*
